### ISSUE TITLE
Q: N Degrees and inner-circle publishing

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#17]
The spec mentions:

> If the remote repository is found to track other remotes, the tracking repository SHALL also transitively track those, up to n degrees out.

Does this stop any information from n degrees out reaching a person at all? The scenario I'm thinking of is the following:

- **Kim**, **Fintan**, and **Xla** are actors in the network, where `n = 1`.
- **Kim** owns **Radicle**
- **Fintan** replicates **Radicle** from Kim, and **Kim** tracks **Fintan**
- **Xla** replicates **Radicle** from **Fintan**, and **Fintan** tracks **Xla**
- **Fintan** accepts a change from **Xla**, and broadcasts the change.

Does **Kim** receive the change or is it ignored because of `n = 1`?

**Comment by kim** [comment]
Depends where you start counting `n` 😆 I see it as “directly tracked + n”, which means in the example that *Kim* replicates *Xla* _via_ *Fintan*. 

I’ll think about a more precise formulation.

**Comment by FintanH** [comment]
Heh, ya exactly. But I don't see how this degrees mechanic does anything then :thinking: where does it stop people from interacting with a user?

**Comment by kim** [comment]
Didn’t we just exemplify this? There’s no direct connection between **Kim** and **Xla**. If **Kim** stops tracking **Fintan**, no information flows back to him.

**Comment by FintanH** [comment]
Right so if **Kim** wanted to block **Xla** then he has to stop tracking **Fintan**, but what if he wants to keep tracking **Fintan**? And in general, in my current understanding, it doesn't matter what `n` is because as long as you track someone you'll potentially receive everyone they track and so on.

Do you get where I'm coming from?

**Comment by kim** [comment]
Ah ok, blocking is a different concern from replication. It depends on how much I hate **Xla** =D  If I just want to unsubscribe from his constant rigmarole, I’d just mute him in the app. If he’s misbehaving according to the protocol, there will be ways to ban him on the network and replication layer. If I want him to be expelled from the community because CoC or whatever - that’s complicated. On the technical level, such a thing could only be successful if creating a new identity is expensive. In our context, I believe the only meaningful way is to associate identity with other identities outside our system (a la keybase), such that your internet reputation is attached to your radicle persona. That doesn’t mean `tonymorris` cannot immediately reappear as `tonymorris42` and so on, but I don’t think there’s a solution to that even in non-decentralised systems.

As for the value of `n`, I think what you’re questioning is how common it is for projects to have a network topology of collaboration as differentiated as the Linux kernel’s, where subsystems have their own communities. That’s valid, although I enjoy the thought of eventually bringing peer-to-peer, crypto-secured policy-enforcified collaboration to the enterprise mwwaahaha

The “social graph” topology becomes more meaningful if you consider a) projects which represent the personal presence of people on the network (i.e. **Kim** might be following **Fintan**, not **Fintan**’s view of **Radicle**), and b) delegating the tracking to seeds (“pubs”), from which a lone maintainer of a hugely popular project can receive notifications about activities in the community without having to store all of the graph locally.

**Comment by FintanH** [comment]
I guess what I'm not getting is what has `n` to do with replication or tracking? As long as it's value is `>= 1` then transitivity will always compress the tracking arrow to a single one. i.e.

Given tracking: `Kim -> Fintan, Fintan -> Xla, Xla -> Rudolfs`
We transitively get: `Kim -> Rudolfs`

So I think I just don't _get_ what `n` is used for :sweat_smile: Unless it's just used for discovery of other projects?

**Comment by kim** [comment]
Kim doesn’t see Rudolfs in your example if n = 1

**Comment by FintanH** [comment]
Ah, so it's the concept of visibility! So Kim doesn't _see_ Rudolfs contributions but they can trickle _back_ to Kim via Rudolfs -> Xla -> Fintan -> Kim?

**Comment by kim** [comment]
> they can trickle *back* to Kim via Rudolfs -> Xla -> Fintan -> Kim?

Only if Xla merges something from Rudolfs.

It’s more of a trust thing: Kim invites Fintan to a house party, and is
fine with Fintan bringing (some of) his friends. If the friends bring their
friends, not sure if Kim would appreciate that.

**Comment by FintanH** [comment]
> Only if Xla merges something from Rudolfs.

Right but there's a path back to Kim via the people in the middle.

> It’s more of a trust thing: Kim invites Fintan to a house party, and is
fine with Fintan bringing (some of) his friends. If the friends bring their
friends, not sure if Kim would appreciate that.

But then this analogy makes me confused again :sweat_smile: Because this would imply that Kim would only allow Xla (Fintan's direct connection) in. But Xla's direct connect, Rudolfs, is not allowed into the party.

If that's the case, then what's the party in this analogy? Like is Xla only allowed to bring the Bavaria that Rudolfs gave him to drink for the party, but Rudolfs can't actually come in? :joy:

**Comment by kim** [comment]
> Right but there's a path back to Kim via the people in the middle.


On the social graph, yes, which is what we want. No information flows back however unless the middle people “promote” it. The middle people don’t have to be people, though.

> Like is Xla only allowed to bring the Bavaria that Rudolfs gave him to drink for the party, but Rudolfs can't actually come in?


Lol, exactly. If the booze was decent, maybe I’ll invite Rudolfs next time.


Alright, let’s consider a scenario involving seeds, maybe that makes it clearer. Say you started a new project, `ruskelldris`, a novel programming language featuring zero-cost dependent methods and linear kinds. You have an account at `plt.boutique`, which runs a seed node, and you ask it to track your project.

I come across your project by browsing the `plt.boutique` web interface, and get really excited. I clone the project, but I don’t have an account at `plt.boutique`, so you won’t notice I did that. Now, I discover a bug in the typechecker, fix it - but how do I submit it to you? A few different options:

* I get an account at `plt.boutique`, make it track my repo (in the context of your project), so by `n > 0` you will notice. Easy.
* I happen to have an account at another seed, `hofbraeuha.us`, which I tell to track the project including my repo.

    * Maybe your client discovers `hofbraeuha.us` via gossip, and you have configured it to notify you of any new followings ("shallow tracking"). It must be that `n > 0` in this case for you to see me.
    * Maybe `plt.boutique` and `hofbraeuha.us` have an agreement to mutually track common projects. By `n > 1`, you'll see my repo.
    * Maybe some guy `pwadl56` has an account on both seeds, and is tracking the project. There's a path `you -> plt.boutique -> pwadl56 -> hofbraeuha.us -> me`. That's four arrows, so it must be the case that `n > 2` to compress it to one.
* Maybe I have a mutual connection with `gpfeil` via our respective "activity feeds", and `gpfeil` is connected to `runaroma`, who is connected to you. If `n > 1`, you'll see it if I @ you.

**Comment by FintanH** [comment]
Ah ok, that's clearer now! Thank you :bowing_man:
