### ISSUE TITLE
Blocking code

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#311]
While testing announcements, @xla and I ran into some less than ideal behaviour but is hard to pin down what a reproducible would look like. The setup is the following:
* Create a peer + user
* Set off the run loop
* Create a project
* Announcements are built from looking at `rad_signed_refs_of`
* Print the events that we see

The behaviour we saw was that the events were blocked due to the building of announcement data. This lead us to look at the call stack of `rad_signed_refs_of` and this call to [`find_reference`](https://github.com/radicle-dev/radicle-link/blob/master/librad/src/git/ext/blob.rs#L82-L85).
We were calling `rad_signed_refs_of` with the `PeerId` of the `Storage`, which admittedly is the wrong usage. This meant that the reference doesn't exist. However, the call to `find_reference` never returns and seems to halt. This seemed to be the cause of blocked events mentioned above.

It's pretty terrifying that a call to find a missing reference blocks up our whole pipeline of events and causes some sort of deadlock.

Correct me if I'm wrong in any of the above details @xla :point_up:

**Comment by kim** [comment]
I suspect find_reference is a red herring. How do you set up
concurrency of polling the run loop future, and the rest?

**Comment by xla** [comment]
The context where we observed the issue was in this integration test:

https://github.com/radicle-dev/radicle-upstream/blob/98e59c2e8462e60c340e844b349ede4e050c9b19/proxy/coco/tests/announcement.rs#L14-L46

The librad `RunLoop` is set up over here:

https://github.com/radicle-dev/radicle-upstream/blob/98e59c2e8462e60c340e844b349ede4e050c9b19/proxy/coco/src/peer.rs#L70-L120

Does that help to get an idea about the concurrency set up?

**Comment by kim** [comment]
If I read this correctly, you're running everything on the global
executor. It might be a good idea to dedicate a tokio runtime to only
the librad protocol loop. Even then, however, you should try to
spawn_blocking the (blocking) git operations for building the
announcements set.

**Comment by xla** [comment]
Thanks for the reminders. What are the benefits of the extra runtime? Given that by default tokio allocates threads equal to the number of cpu threads we should have enough room to never starve that, given of course that we schedule blocking operations appropriately with `spawn_blocking`.

In this instance we were facing the issue that this call would never return, as in the caller was stuck:

https://github.com/radicle-dev/radicle-link/blob/555de1a1157a9341e82708049247cb8dfeb7f962/librad/src/git/ext/blob.rs#L82-L85

Not so much that we were not seeing arrival of protocol events.

**Comment by kim** [comment]
> What are the benefits of the extra runtime?

You can never forget to wrap a piece of blocking code in `spawn_blocking`. 

Look, I've seen `std::sync::Mutex` (instead of `futures::lock::Mutex`) deadlock when used in an async context, so I'm not too surprised that you encounter erratic behaviour when performing actual blocking IO inside a future -- I have no idea why this is, perhaps it's trying to preempt the task?

I still don't think the piece of code you're linking to has anything to do with the issue. If `spawn_blocking` doesn't fix it, perhaps try attaching `gdb` to see what's going on. 

Or maybe it is actually waiting on a sync mutex?

**Comment by kim** [comment]
whp not a `librad` issue.

Feel free to reopen if you have more evidence.

**Comment by xla** [comment]
> Look, I've seen `std::sync::Mutex` (instead of `futures::lock::Mutex`) deadlock when used in an async context, so I'm not too surprised that you encounter erratic behaviour when performing actual blocking IO inside a future -- I have no idea why this is, perhaps it's trying to preempt the task?

The code that triggered this doesn't use a `std::sync::Mutex`. I don't have more evidence that it is a librad issue, but there is no indication that it is lock contention. When we traced we got down to https://github.com/radicle-dev/radicle-link/blob/555de1a1157a9341e82708049247cb8dfeb7f962/librad/src/git/ext/blob.rs#L82-L85

In turn resolves to

https://github.com/rust-lang/git2-rs/blob/218a2b380a6eae17ec8a7499683a5be2232cb659/src/repo.rs#L1454-L1462

which at this point if we got that far, there is no `await` yield point and as far as I can tell also no Mutex, at least in the Rust part of git2. Maybe noteworthy all the way in the proxy we do the call to `rad_signed_refs_of` on a `TryToOwned` `Storage`.

**Comment by kim** [comment]
Your best bet is to build an executable from this which you can step
through using gdb. There is no reason this function should block
unless there is some interference with the async context -- but it's
**your** async context, not librad's. Another possibility I could see
is that you might be running out of fds -- you're apparently creating
new repository handles all the time.
