### ISSUE TITLE
Use ed25519-zebra instead of libsodium

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#315]
Reasons:

1. `libsodium` makes for slower builds (see also radicle-dev/radicle-keystore#7)
2. [`ed25519-zebra`](https://crates.io/crates/ed25519-zebra) has a batch verification API, which could potentially give a nice speedup for some things
3. The motivation for creating `ed25519-zebra` was that the ZCash project realised that a bugfix(!) in the way `libsodium` validates signatures could break their consensus. While not much of a concern for us immediately, their solution is attractive for two reasons:

    i. There is an unambiguous spec of how signature validation is supposed to work in `radicle-link` (ZIP 215)
    ii. It is, in essence, _more compatible_ with all kinds of ed25519 signatures, so we should never need to worry about upgrades

**Comment by cloudhead** [comment]
I've started working on this, as it's a nice task to do between other tasks, but encountered some road blocks, namely the lack of `Ord/Eq` on their `VerificationKey`. I'm going to see if I can patch it upstream.

**Comment by cloudhead** [comment]
PR is here: https://github.com/ZcashFoundation/ed25519-zebra/pull/31

It's the only change needed for things to compile.

**Comment by hdevalence** [comment]
By the way, on the batch verification point, it looks like `radicle-link` uses async.  I don't have any context about *how* you use ed25519, so I don't know whether this approach will be useful, but we've been working on an asynchronous batch verification interface as part of Zebra.

There's a description of the generic middleware that provides the interface [here]( https://doc.zebra.zfnd.org/tower_batch/index.html ) and the test code for that crate uses ed25519 verification as the [example case]( https://github.com/ZcashFoundation/zebra/blob/main/tower-batch/tests/ed25519.rs#L18-L85 )

What's really cool is that this middleware can be composed with a single-verification fallback in case of batch failure, and put into a `static` to provide a [global, shared verification context](https://github.com/ZcashFoundation/zebra/blob/main/zebra-consensus/src/primitives/redjubjub.rs#L22-L49). This batches any contemporaneous signature verifications from anywhere in the program, with a configurable upper bound on the latency of any individual signature verification. Because the ZIP215 rules make batch verification identical to single verification, and because the resulting service does single-verification fallback in case of failure, each verification request has identical results as if single verification had been used.

But unlike a conventional batch verification API, batches are managed implicitly rather than explicitly, so there's no need to have separate code paths for the batched / non-batched case, and there's no need to choose the level of batching in advance.

We've been focused on shipping Zebra, so this code isn't fully reusable yet, but we'd like to get there, so if it sounds like this would fit your use case I'd be interested in trying to map out what would be required to make it work.

**Comment by kim** [comment]
@hdevalence Thanks for those pointers! 

We're currently constrained by `libgit2` -- the "multisigs" we verify are git commits, and to walk git histories concurrently we'd need to employ OS threads. There could still be opportunities to exploit async, for example when we have many heads (with relatively short histories, so the FFI calls would yield relatively quickly) for which we need to verify if they agree. There are also plans to persist past verification results (not yet implemented), such that we minimise the time spent revwalking, and again end up with smaller FFI calls.

I see that you set things up so verification tasks get submitted through a channel, so I think if that wasn't tied to `tower`, we could make use of your code directly. I'm also not very familiar with `tower`, so let me play around with it for a bit.
