### ISSUE TITLE
Add `list` for Project & User

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-link#418]
When I was looking at the documentation on the `next` branch, I noticed that we were missing functionality to list users and projects.

**Comment by kim** [comment]
[It's here](https://github.com/radicle-dev/radicle-link/blob/next/librad/src/git/identities/any.rs#L69). I did not provide a precomposed [`filter_map`](https://github.com/radicle-dev/radicle-link/blob/next/seed/src/project.rs#L64), because I would like users to be aware that this incurs accessing _every_ identity blob (in order to figure out what type it has).

**Comment by FintanH** [comment]
Ah cool! I missed the `any` submodule when going through the docs.
