### ISSUE TITLE
Protocol versioning

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-link#440]
With updates to the layout of the storage - frequently in the current development phase and later when doing major breaking upgrades - peers can end up replicated data which breaks their programmatic access to the monorepo. To prevent such cases and enable graceful upgrade paths of network participants should we introduce some form of versioning? Which can be used during a handshake to communicate the protocol - potentially versions of components as well - and reject if not matching/compatible.

**Comment by kim** [comment]
We have this already via [ALPN](https://github.com/radicle-dev/radicle-link/blob/d470e0162387579efc5869236dbc4cefb3b8366d/librad/src/net/quic.rs#L43).

I am skeptical towards finer grained versioning -- the curse of uncoördinated distributed systems is that they, in theory, have to maintain forwards- and backwards-compatibility forever. Since we are releasing before the protocol has stabilised, I am expecting that we'll break early adopter's installations, but after that an incompatible protocol upgrade should become a last resort.

Note that ALPN leaves the possibility to run >1 protocol versions in parallel (if there is a mapping), but will reject connections on the transport layer if no common protocol could be negotiated.

**Comment by xla** [comment]
Great, totally missed the version part of ALPN.
