### ISSUE TITLE
Use stable rust

### ISSUE THREAD

**Issue by d-xo** [radicle-dev/radicle-link#476]
It's not a huge deal, but I thought it was worth mentioning here. The usage of unstable features means that a from source build in `nixpkgs` is not possible since the unstable compiler versions are only available via the [mozilla nixpkgs overlay](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/rust.section.md#using-the-rust-nightlies-overlay)

Speaking with my `nixpkgs` contributer hat on, I would be happy to be able to compile this using stable rust and transition the `radicle-upstream` package to be a from source build.

I think this is also probably blocking the creation of a `radicle-seed` package inside of `nixpkgs`.

See [this pr](https://github.com/NixOS/nixpkgs/pull/105674) for discussion.

**Comment by kim** [comment]
Unfortunately, this is somewhat unlikely to happen before we either approaching a stable version of this library, or (some of) the unstable features land in stable Rust, whichever comes first. It is _probably_ not a huge deal, but iirc even the crippled version of GATs in unstable reduces the perpetual pain of finding new workarounds for language deficiencies.

Due to some fatigue in that respect, it is not a top priority to make the crates here build under stable Rust. If this is a blocker, help would be appreciated nevertheless!

**Comment by SergeyDjam** [comment]
This problem in ROSA Linux too
