### ISSUE TITLE
linkd crashing from radicle-cli's test script

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/radicle-link#798]
Running the radicle-cli's [test contributor workflow script](https://github.com/radicle-dev/radicle-cli/blob/master/scripts/contributor-workflow-setup.sh) is causing the latest version of linkd to fail over.

```
  2022-10-18T19:25:58.782152Z ERROR quinn::builders: I/O error: Invalid argument (os error 22)
    at [home]/.cargo/registry/src/github.com-1ecc6299db9ec823/quinn-0.7.2/src/builders.rs:79
```

**Comment by FintanH** [comment]
I'm under the impression that the version of `radicle-cli` that uses `linkd` is not going to be officially published, so I don't think it's worth digging into this, personally.

If you'd like to dig in deeper and post your findings here, I'm happy to review them and answer any questions. A good start would be to detail what the "test contributor workflow script" does because I've never interacted with it.

**Comment by slack-coder** [comment]
> I'm under the impression that the version of `radicle-cli` that uses `linkd` is not going to be officially published, so I don't think it's worth digging into this, personally.

Noted, at least we have it documented here for others.

> If you'd like to dig in deeper and post your findings here, I'm happy to review them and answer any questions. A good start would be to detail what the "test contributor workflow script" does because I've never interacted with it.

Good point, I updated the issue with a link to the test script in question.
