### ISSUE TITLE
Peer Update Semantics

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-link#84]
As discussed in #58, peers SHOULD maintain a **project** which provides
information about which other projects it provides.

One way to do this is an "activity feed", which allows to convey temporal
information ("massi@qwertyuiop followed arch-linux@poiuytrewq"). Another way is
to simply copy the `rad/id` branch of all locally available projects into a
single one.

Either way, since it is just-another-project, it will be replicated on the
network like any other project, such that updates can be propagated even if the
origin peer is not reachable.

The scope of this ticket is similar to #53

**Comment by kim** [comment]
tagging @cloudhead: would be great to get some product input on this, re activity feed or not

**Comment by cloudhead** [comment]
We're definitely going to want things beyond project lists down the line, as in your example: `"cloudhead tracked <project>"`, `"kim published 5 commits to <project>"`, `"cloudhead created <project>"` etc. One question I have though is whether this functionality can be shared with how we do notifications (eg. "you were mentioned in issue #213"), because *that* is the big feature for us: knowing when someone mentioned you on some project, or started tracking one of your projects. Regarding this, I have a few thoughts/questions that may help ellucidate how we think about this:

1. Where is the logic that decides what projects to track? If a maintainer of a project starts tracking a new repo/peer, which part of the system will trigger the tracking of that new repo by a user tracking the project? This would be an "update" that has some kind of direct consequence on network topology.

2. Are we generally thinking of updates/notifications as (a) Download all data locally, and keep track of what you've already seen, and for each thing you *haven't* seen, create a notification (diff-based), or (b) Follow some kind of per-project stream of events and generate notifications from there.

**Comment by kim** [comment]
Thanks @cloudhead

> We're definitely going to want things beyond project lists down the
> line, as in your example: `"cloudhead tracked <project>"`, `"kim
> published 5 commits to <project>"`, `"cloudhead created <project>"` etc.
> One question I have though is whether this functionality can be shared
> with how we do notifications (eg. "you were mentioned in issue #213"),
> because *that* is the big feature for us: knowing when someone mentioned
> you on some project, or started tracking one of your projects.

There's a few different things in here:

* Mentions are tricky, because they are a) payload data and b) hard to type. If
  we mandate that this goes through tooling (an editor), we _could_ emit a
  structured event somewhere. But generally, it seems less brittle to do it on
  read (which may also cause your client to actually go and fetch that user
  identity).
* If I'm mentioned in a project I'm not tracking at all, the only path through
  which this could be surfaced to me is through projects which represent users,
  and the social graph being connected somehow. That's again tricky, because I'm
  following that _user_, but not the issue itself, so that user has to mention
  the mention in the data feed I'm subscribed to.
* I've been thinking about tracking trackings on and off -- generally, there's
  two ways: either the peer who initiates the tracking explicitly announces this
  (or decides not to), or the other side intercepts full clones and announces
  *that*. The second option will of course create duplicate events (with
  different timestamps), and is dubious from a privacy perspective. So I'd be
  leaning towards the first option.
* Lastly, the "published X commits" event is probably the only one that could be
  generated just by comparing two snapshots (before and after fetch).

> 1. Where is the logic that decides what projects to track? If a
> maintainer of a project starts tracking a new repo/peer, which part of
> the system will trigger the tracking of that new repo by a user tracking
> the project? This would be an "update" that has some kind of direct
> consequence on network topology.

I'm not sure what you mean here: if I'm tracking the maintainer of a project,
any new remotes that appear below that "namespace" will end up on my machine,
too. I'm trying to condense this down to a single function [fetch
here](https://github.com/radicle-dev/radicle-link/pull/82/files#diff-c17ba2ce1d7143cc0c5d85302447f2c1R296).
Of course we can think about how to intercept before and after that fetch
operation.

If that maintainer starts tracking an entirely different project, however,
there's no way to know, unless I'm also following some kind of personal update
feed. Or, as outlined in the ticket, a snapshot of the project identities
tracked by the maintainer's PeerId -- but then, the maintainer may have multiple
PeerIds (devices). This would, again, speak more in favour of the feed model,
because it could be maintained from multiple devices (just like any other
project).

Regardless, whether or not to track new projects is a user decision. The only
exception is when verifying metadata -- if user identities need to be resolved
to external projects, the system would do this implicitly.

> (b) Follow some kind of per-project stream of events and generate
> notifications from there.

Per-project? Which types of events were you thinking of for this?

**Comment by cloudhead** [comment]
Ok this clears a few things up, thanks.

> * Mentions are tricky, because they are a) payload data and b) hard to type. If we mandate that this goes through tooling (an editor), we _could_ emit a structured event somewhere. But generally, it seems less brittle to do it on read (which may also cause your client to actually go and fetch that user identity).

Yeah, doing it on read makes more sense. Only limitation as you said is that you can't be mentioned from a project you aren't tracking. For now that's totally fine, but it's something to think about.

> Per-project? Which types of events were you thinking of for this?

Things like:

* Issue opened/closed
* Revision merged
* New comment on issue
* Review requested on revision

I think these are a little different from the "mention" case, since they are "actions", and thus can trigger some kind of event to be generated in a feed. Of course, we can try to deduce them by comparing prev/current project data, but that might be cumbersome.

**Comment by kim** [comment]
> * Issue opened/closed
> * Revision merged
> * New comment on issue
> * Review requested on revision

Hm, so we're talking about about events to be published elsewhere (e.g. my
personal feed)? If the state of issues/revisions is computed by a reducer over
a "Merkle DAG" of operations, then we already have all the actions. Only a
different transformation might be needed to yield a list of things which
happened since the last computed state.

**Comment by cloudhead** [comment]
You're right, I didn't think about this. The natural form of the data will already be in the shape we want, ie. an event log of sorts. This means we don't really need a first-class "user feed" object afaict, as the reducer can also create these for each user it enouncters on the fly.

**Comment by kim** [comment]
Depends on what we mean by “user feed” :) There are three things we’re considering here, I think:

* For every user, there might be some local view of things which happened (like the GH activity feed), which interleaves events from different sources.
* There might be a **published** feed per-user, like in SSB. This is useful for expanding your filter bubble: if I track @cloudhead’s SSB-style feed, I can discover other projects and users.
* There might also be a published SSB-style feed **per-peer**, where the only difference to a user-feed is that it could exist without a user identity attached to it (because it’s a machine).

The question is if and how the contents of each differ — my thinking is that the latter two should be much less detailed, so as to not replicate stuff one will never be interested in.

**Comment by cloudhead** [comment]
Yeah, so let's break it down:

* *Things that happened around projects I **track***, eg. mentions, issue lifecycle, merged changes, comments. We should get this for free via the issue/revision reducer. This is the backbone of the notification system.
* *Things that happened **outside** of projects I track*, eg. my friend (whatever this means) started a new project, or started tracking a project or user. We don't get this for free, so this would require a special-purpose entity, (eg. `Feed`, to complement `Project` and `User`), or simply be part of the `User` entity. This is the backbone of the *discovery/explore* system, to expand your horizons.
* *Things that I happen to hear about due to which peers are connected to me*, same events as above, but not necessarily socially-connected to me in any way. This is some form of "opportunistic" discovery. Less important, but still can be nice to have.

I think the contents of the 2nd/3rd are less detailed as you said, and could just be for example:
```rust
enum EventType { NewProject(ProjectId), ProjectTracked(UserId, ProjectId), UserTracked(UserId, UserId)
struct Event(EventType, Timestamp, Signature);
type Feed = Vec<Event>;
```

**Comment by kim** [comment]
Superseded (#214, #212, ...)
